<?php

return [

    'privacidade' => '<p>Serão requeridos no site os dados do usuário nos momentos de cadastro e login, não será requerido nenhum número de cartão ou CPF até mesmo RG dos mesmos.</p>
<p>Durante cadastro do usuário será requerido o email, no qual deverá ser um email valido, existente e que o usuário acesse regularmente. Será necessária também a criação de uma senha que não será divulgada a ninguém, senão ao usuário. Os dados do usuário não serão revelados a ninguém.</p>
<p>O Email do usuário será utilizado para o cadastro do usuário, e, somente se o usuário concordar, o email será utilizado para receber comunicados de atualizações da comunidade, e do site em si</p>
<p>Assim como citado anteriormente, o único dado pessoal requisitado do usuário será o Email de uso regular do usuário,  outros dados serão dispensáveis durante o cadastro e utilização do site.</p>
<p>Cookies ?
<p>Para a utilização e visualização dos conteúdos disponíveis de forma gratuita no site, será necessário que o usuário esteja conectado no site com sua conta de usuário.</p>
<p>Não será divulgado a terceiros os dados dos usuários, muito menos a utilização comercial de quaisquer dados fornecidos pelos mesmos.</p>
<p>Os botões de compartilhamento serão vinculados as contas dos usuários em suas respectivas redes sociais, tendo em vista que será oferecida uma opção de cadastro utilizando a conta das redes sociais dos mesmos.</p>
<p>Em caso de perca de dados dos usuários (senha ou email) poderá ser solicitado uma troca de senha, os dados referentes a troca serão encaminhados ao usuário por meio do email que foi cadastrado previamente.</p>
<p>Em caso de mudança nos termos de utilização e privacidade, um email será encaminhado ao usuário, assim como uma notificação, quando usuário acessar pela primeira vez o site, após as mudanças nos termos.</p>
<p>Este documento ficará permanentemente no site, se encontrando no menu, aonde estará de maneira que seu acesso seja fácil aos usuários que desejam visualizar os termos.</p>
Quaisquer duvidas referentes a esses termos ou qualquer outro conteúdo do site, poderão ser retiradas ao acessar o menu “fale conosco”, ou na sessão duvidas.</p>',

    'termos' => '<p>Ao utilizar e participar de forma ativa no Astrogame, de qualquer das formas que o website permite, o Utilizador declara ter lido e aceitar cumprir os presentes Termos e Condições. O Astrogame reserva-se o direito – mas não a obrigação – de, perante o não cumprimento destes Termos e Condições, eliminar todo e qualquer conteúdo que os infrinja, bem como restringir e/ou bloquear o acesso do Utilizador infrator à participação no website, sem qualquer aviso prévio.</p>
      <p>Na utilização que fizer deste website (incluindo na submissão, envio ou publicação de conteúdos que fizer para o Astrogame), o Utilizador está obrigado e declara aceitar e cumprir a legislação aplicável, e concretamente o Código do Direito de Autor e dos Direitos Conexos, o Código da Propriedade Industrial e a Lei da Criminalidade Informática.</p>
      <p>O Utilizador está também obrigado a declarar agir de boa-fé e a fazer uma utilização do Astrogame que não ofenda quaisquer direitos de terceiros. Particularmente, compromete-se a não submeter qualquer conteúdo ou fazer uma participação que constitua qualquer ataque em função da raça, nacionalidade, origem étnica, religião, convicção política ou sexo; que constitua difamação, incitação ao furto, fraude, violência, terrorismo, sadismo, prostituição, pedofilia, bem como que empregue conteúdos de carácter obsceno, indecoroso ou pornográfico.</p>
      <p>O Utilizador apenas está autorizado a fazer uso dos conteúdos presentes no Astrogame para fins estritamente pessoais, sendo-lhe expressamente proibido publicar, reproduzir, difundir, distribuir ou, por qualquer outra forma, tornar os conteúdos acessíveis a terceiros, para fins de comunicação pública ou de comercialização, como por exemplo colocando-os disponíveis noutro site, serviço on-line ou em cópias de papel. Está igualmente vedada qualquer transformação dos conteúdos.</p>
      <p>É também expressamente proibido ao Utilizador criar ou introduzir no Astrogame tipos de vírus ou programas que o danifiquem, direta ou indiretamente.</p>
      <p>O Astrogame, e o respectivo conteúdo, tem finalidade exclusivamente lúdica, pelo que nada neste website constitui um conselho, não dispensando o conselho profissional, nem estabelece qualquer relação contratual.</p>
      <p>O Utilizador é o único responsável pelos prejuízos, diretos ou indiretos, causados a si próprio, ao Astrogame ou a terceiros, relacionados com a utilização que fizer do Astrogame, comprometendo-se a proceder às indenizações necessárias, em virtude de qualquer ação, reclamação ou condenação a que essa utilização dê origem.</p>
      <p>O Astrogame não garante que os serviços prestados por este website funcionem de forma contínua ou que se encontrem livres de erros, vírus ou outros elementos prejudiciais.</p>
      <p>O Astrogame não é responsável pela exatidão, qualidade, segurança, legalidade ou licitude, incluindo o cumprimento das regras respeitantes a direitos de autor e direitos conexos, relativamente aos conteúdos, produtos ou serviços contidos neste website que tenham sido criados ou fornecidos por membros, utilizadores, anunciantes ou parceiros comerciais, bem como por qualquer informação contida em sites de terceiros para os quais este website estabeleça ligações.
      <p>
      <p>O Utilizador declara autorizar, a título gratuito, a divulgação, publicação, utilização e exploração dos conteúdos, textos, dados, imagens ou programas por si enviados para o Astrogame.
      <p>
      <p>O Utilizador declara igualmente que:<br>
         tem plena legitimidade para autorizar a utilização previamente mencionada e, concretamente, que obteve e dispõe dos necessários direitos e autorizações a título de direitos de autor e assegurou os pagamentos eventualmente devidos a terceiros legítimos titulares de direitos sobre os conteúdos, textos, dados, imagens ou programas por si enviados para Astrogame, para efeitos da sua utilização nos termos previstos na presente declaração; sobre o direito de autorizar a utilização dos conteúdos, textos, dados, imagens ou programas por si enviados para o Astrogame constantes da presente declaração, não existe qualquer reclamação ou processo instaurado ou alguma contestação relativamente à sua titularidade por parte de terceiros; não existe nenhum compromisso nem nenhuma condição decorrente de relações jurídicas eventualmente existentes entre o utilizador e terceiros que impeça ou condicione, de algum modo, a execução total ou parcial da presente declaração nos termos nela definidos. O Astrogame exime-se de qualquer responsabilidade resultante da falta de veracidade do anteriormente declarado ou da violação pelo Utilizador de quaisquer direitos ou interesses legitimamente protegidos de terceiros. O Astrogame reserva-se no direito de livremente (sem obrigatoriedade de invocar qualquer motivo) e em qualquer momento, remover ou não publicar, total ou parcialmente, quaisquer conteúdos, textos, dados, imagens, aplicações ou programas, editados por si ou pelo Utilizador, sem que por tal fato advenha qualquer direito de indenização ou compensação para o Utilizador ou quaisquer terceiros.
      </p>
      <p>Não existe qualquer obrigação do Astrogame em guardar os conteúdos, textos, dados, imagens ou programas publicados neste website, podendo os mesmos ser destruídos a qualquer momento, sem que por tal fato advenha qualquer direito de indenização para o Utilizador ou quaisquer terceiros.</p>',
];
